apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- rbac.yaml
- deployment.yaml
- crds/clusters.openmcp.cloud_accessrequests.yaml
- crds/clusters.openmcp.cloud_clusterprofiles.yaml
- crds/clusters.openmcp.cloud_clusterrequests.yaml
- crds/clusters.openmcp.cloud_clusters.yaml
- crds/kind.clusters.openmcp.cloud_providerconfigs.yaml
- crds/openmcp.cloud_clusterproviders.yaml
- crds/openmcp.cloud_platformservices.yaml
- crds/openmcp.cloud_serviceproviders.yaml
- cluster-providers/kind.yaml
- extra/crossplane-provider.yaml
