apiVersion: openmcp.cloud/v1alpha1
kind: ClusterProvider
metadata:
  name: "kind"
spec:
  image: "ghcr.io/openmcp-project/images/cluster-provider-kind:v0.0.15"
  extraVolumeMounts:
  - mountPath: /var/run/docker.sock
    name: docker
  extraVolumes:
  - hostPath:
      path: /var/run/host-docker.sock
      type: Socket
    name: docker
