apiVersion: crossplane.services.openmcp.cloud/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  versions:
    - version: v2.0.2
      chart:
        url: ghcr.io/openmcp-project/charts/crossplane:2.0.2
      image:
        url: xpkg.crossplane.io/crossplane/crossplane:v2.0.2
    - version: v1.20.1
      chart:
        url: ghcr.io/openmcp-project/charts/crossplane:1.20.1
      image:
        url: xpkg.crossplane.io/crossplane/crossplane:v1.20.1
  providers:
    availableProviders:
      - name: provider-kubernetes
        package: xpkg.upbound.io/upbound/provider-kubernetes
        versions:
          - v0.16.0