apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../resources/openmcp
images:
  - name: <openmcp/openmcp-operator>
    newName: ghcr.io/openmcp-project/images/openmcp-operator
    newTag: v0.17.1

secretGenerator:
  - name: openmcp-operator-config
    namespace: openmcp-system
    files:
      - config=config/openmcp-operator-config.yaml

patches:
  - target:
      kind: Deployment
      name: openmcp-operator
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/args/1
        value: --environment=Dev
      - op: replace
        path: /spec/template/spec/containers/0/args/1
        value: --environment=Dev
